{{- if eq .Values.monitoringKubernetesControlPlane.internal.kubeApiserver.accessType "ThroughNode" }}
  {{- if eq .Values.monitoringKubernetesControlPlane.internal.kubeApiserver.throughNode.authenticationMethod "Certificate" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-control-plane-kube-apiserver-client-cert
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: Opaque
data:
  client.crt: {{ .Values.monitoringKubernetesControlPlane.internal.kubeApiserver.clientCertificate.clientCrt | b64enc }}
  client.key: {{ .Values.monitoringKubernetesControlPlane.internal.kubeApiserver.clientCertificate.clientKey | b64enc }}
  {{- end }}
{{- end }}
