---
# TODO remove after 1.32 release from 1.30 we use grafana-datasources secret
# Leave this cm for prevent mount volume error while terminating pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "grafana")) | nindent 2 }}
data:
  prometheus.yaml: |+
    apiVersion: 1
    deleteDatasources:
      - name: trickster
        orgId: 1
      - name: trickster-longterm
        orgId: 1
{{- if eq (int .Values.prometheus.longtermRetentionDays) 0 }}
      - name: longterm
        orgId: 1
{{- end }}
{{- if (include "helm_lib_ha_enabled" .) }}
      - name: main-0
        orgId: 1
      - name: main-1
        orgId: 1
{{- end }}
    datasources:
     - name: main
       type: prometheus
       access: direct
       orgId: 1
       url: /trickster/main
       version: 1
       isDefault: true
       jsonData:
         httpMethod: POST
         timeInterval: {{ .Values.prometheus.scrapeInterval | default "30s" }}
{{- if ne (int .Values.prometheus.longtermRetentionDays) 0 }}
     - name: longterm
       type: prometheus
       access: direct
       orgId: 1
       url: /trickster/longterm
       version: 1
       jsonData:
         httpMethod: POST
         timeInterval: {{ .Values.prometheus.longtermScrapeInterval | default "5m" }}
{{- end }}
{{- if (include "helm_lib_ha_enabled" .) }}
     - name: main-uncached-0
       type: prometheus
       access: direct
       orgId: 1
       url: /prometheus-main-0
       version: 1
       jsonData:
         httpMethod: POST
         timeInterval: {{ .Values.prometheus.scrapeInterval | default "30s" }}
     - name: main-uncached-1
       type: prometheus
       access: direct
       orgId: 1
       url: /prometheus-main-1
       version: 1
       jsonData:
         httpMethod: POST
         timeInterval: {{ .Values.prometheus.scrapeInterval | default "30s" }}
{{- end }}
{{ if .Values.prometheus.internal.grafana.additionalDatasources }}
  additional_datasources.yaml: |+
    apiVersion: 1
    datasources:
      {{- .Values.prometheus.internal.grafana.additionalDatasources | toYaml | nindent 6 }}
{{- end }}
