{{- define "trickster_client_tls_cert_params" }}
secureJsonData:
  tlsClientCert: |
    {{- .Values.prometheus.internal.prometheusAPIClientTLS.certificate | nindent 4 }}
  tlsClientKey: |
    {{- .Values.prometheus.internal.prometheusAPIClientTLS.key | nindent 4 }}
{{- end }}

{{- define "trickster_tls_params" }}
tlsAuth: true
tlsAuthWithCACert: false
tlsSkipVerify: true
{{- end }}

{{- define "render_grafana_datasources_config" }}
apiVersion: 1
deleteDatasources:
 - name: trickster
   orgId: 1
 - name: trickster-longterm
   orgId: 1

{{- if eq (int .Values.prometheus.longtermRetentionDays) 0 }}
 - name: longterm
   orgId: 1
{{- end }}

{{- if (include "helm_lib_ha_enabled" .) }}
 - name: main-0
   orgId: 1
 - name: main-1
   orgId: 1
{{- end }}

datasources:
 - name: main
   type: prometheus
   access: proxy
   orgId: 1
   url: https://trickster.d8-monitoring.svc.{{ .Values.global.discovery.clusterDomain }}/trickster/main
   version: 1
   isDefault: true
   jsonData:
     httpMethod: POST
     timeInterval: {{ .Values.prometheus.scrapeInterval | default "30s" }}
     {{- include "trickster_tls_params" . | nindent 5 }}
   {{- include "trickster_client_tls_cert_params" . | nindent 3 }}


{{- if ne (int .Values.prometheus.longtermRetentionDays) 0 }}
 - name: longterm
   type: prometheus
   access: proxy
   orgId: 1
   url: https://trickster.d8-monitoring.svc.{{ .Values.global.discovery.clusterDomain }}/trickster/longterm
   version: 1
   jsonData:
     httpMethod: POST
     timeInterval: {{ .Values.prometheus.longtermScrapeInterval | default "5m" }}
     {{- include "trickster_tls_params" . | nindent 5 }}
   {{- include "trickster_client_tls_cert_params" . | nindent 3 }}
{{- end }}

{{- if (include "helm_lib_ha_enabled" .) }}
 - name: main-uncached-0
   type: prometheus
   access: proxy
   orgId: 1
   url: https://prometheus-main-0.d8-monitoring.svc.{{ .Values.global.discovery.clusterDomain }}:9090
   version: 1
   jsonData:
     httpMethod: POST
     timeInterval: {{ .Values.prometheus.scrapeInterval | default "30s" }}
     {{- include "trickster_tls_params" . | nindent 5 }}
   {{- include "trickster_client_tls_cert_params" . | nindent 3 }}
 - name: main-uncached-1
   type: prometheus
   access: proxy
   orgId: 1
   url: https://prometheus-main-1.d8-monitoring.svc.{{ .Values.global.discovery.clusterDomain }}:9090
   version: 1
   jsonData:
     httpMethod: POST
     timeInterval: {{ .Values.prometheus.scrapeInterval | default "30s" }}
     {{- include "trickster_tls_params" . | nindent 5 }}
   {{- include "trickster_client_tls_cert_params" . | nindent 3 }}
{{- end }}

{{- end }}

{{- define "render_grafana_additional_datasources_config" }}

apiVersion: 1
datasources:
  {{- .Values.prometheus.internal.grafana.additionalDatasources | toYaml | nindent 2 }}

{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "grafana")) | nindent 2 }}
data:
  prometheus.yaml: {{ include "render_grafana_datasources_config" . | b64enc | quote }}
{{ if .Values.prometheus.internal.grafana.additionalDatasources }}
  additional_datasources.yaml: {{ include "render_grafana_additional_datasources_config" . | b64enc | quote }}
{{- end }}
