---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: cert-manager-webhook-ca
  namespace: d8-cert-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhook")) | nindent 2 }}
  annotations:
    cert-manager.io/allow-direct-injection: "true"
data:
  ca.crt: {{ .Values.certManager.internal.webhookCACrt | b64enc }}
  tls.crt: {{ .Values.certManager.internal.webhookCACrt | b64enc }}
  tls.key: {{ .Values.certManager.internal.webhookCAKey | b64enc }}
