---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-metrics-adapter-prometheus-api-client-tls
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.prometheusMetricsAdapter.internal.prometheusAPIClientTLS.certificate | b64enc }}
  tls.key: {{ .Values.prometheusMetricsAdapter.internal.prometheusAPIClientTLS.key | b64enc }}
