{{- if (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: extended-monitoring-exporter
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "prometheus" "main")) | nindent 2 }}
spec:
  jobLabel: app
  podMetricsEndpoints:
  - port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
      cert:
        secret:
          name: prometheus-scraper-tls
          key: tls.crt
      keySecret:
        name: prometheus-scraper-tls
        key: tls.key
    honorLabels: true
    scrapeTimeout: 25s
    relabelings:
    - regex: endpoint|namespace
      action: labeldrop
    - sourceLabels: ["pod"]
      targetLabel: pod
  selector:
    matchLabels:
      app: extended-monitoring-exporter
  namespaceSelector:
    matchNames:
    - d8-monitoring
{{- end }}
