{{- $context := . }}
{{- range $instance := .Values.monitoringKubernetesControlPlane.internal.kubeEtcd }}
  {{- if eq $instance.accessType "ThroughNode" }}
    {{- if or (eq $instance.throughNode.authenticationMethod "Certificate") (eq $instance.throughNode.authenticationMethod "D8PKI") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-control-plane-kube-etcd-client-cert-{{ $instance.name | lower }}
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list $context) | nindent 2 }}
type: Opaque
data:
  client.crt: {{ $instance.clientCertificate.clientCrt | b64enc }}
  client.key: {{ $instance.clientCertificate.clientKey | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}
