- name: coreos.kube-state-metrics
  rules:
  - alert: DeploymentGenerationMismatch
    expr: max(kube_deployment_status_observed_generation != kube_deployment_metadata_generation) by (namespace, deployment)
    for: 15m
    labels:
      severity_level: 4
    annotations:
      plk_protocol_version: "1"
      description: Observed deployment generation does not match expected one for
        deployment {{$labels.namespace}}/{{$labels.deployment}}
      summary: Deployment is outdated
  - alert: KubeStateMetricsDown
    expr: absent(up{job="kube-state-metrics"} == 1)
    for: 5m
    labels:
      impact: deadly
      likelihood: certain
    annotations:
      plk_protocol_version: "1"
      plk_markup_format: markdown
      description: |-
        Нет запущенных подов kube-state-metrics.
        При отсутствии корректно работающих подов kube-state-metrics большая часть графиков и алертов перестает работать.
        Т.е. мы не сможем получить корректную информацию от мониторинга.

        Что нужно посмотреть:
        1. Логи деплоймента: `kubectl -n d8-monitoring describe deploy kube-state-metrics`
        2. Найти поды и посмотреть его состояние: `kubectl -n d8-monitoring describe pod -l app=kube-state-metrics`
      summary: >
        Kube-state-metrics под недоступен
#  - alert: DeploymentReplicasNotUpdated
#    expr: max(((kube_deployment_status_replicas_updated != kube_deployment_spec_replicas)
#      or (kube_deployment_status_replicas_available != kube_deployment_spec_replicas))
#      unless (kube_deployment_spec_paused == 1)) by (namespace, deployment)
#    for: 15m
#    labels:
#      severity_level: 4
#    annotations:
#      description: Replicas are not updated and available for deployment {{$labels.namespace}}/{{$labels.deployment}}
#      summary: Deployment replicas are outdated
#  - alert: DaemonSetRolloutStuck
#    expr: max(kube_daemonset_status_number_ready / kube_daemonset_status_desired_number_scheduled) by (namespace, daemonset)
#      * 100 < 100
#    for: 15m
#    labels:
#      severity_level: 4
#    annotations:
#      description: Only {{$value}}% of desired pods scheduled and ready for daemon
#        set {{$labels.namespace}}/{{$labels.daemonset}}
#      summary: DaemonSet is missing pods
#  - alert: K8SDaemonSetsNotScheduled
#    expr: max(kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_current_number_scheduled) by (namespace, daemonset)
#      > 0
#    for: 10m
#    labels:
#      severity_level: 4
#    annotations:
#      description: '{{$value}} of desired pods are not scheduled for daemon set {{$labels.namespace}}/{{$labels.daemonset}}'
#      summary: Daemonsets are not scheduled correctly
#  - alert: DaemonSetsMissScheduled
#    expr: max(kube_daemonset_status_number_misscheduled) by (namespace, daemonset) > 0
#    for: 10m
#    labels:
#      severity_level: 4
#    annotations:
#      description: '{{$value}} pods of daemon set {{$labels.namespace}}/{{$labels.daemonset}} are running where they are not supposed to run.'
#      summary: Daemonsets are not scheduled correctly
#  - alert: PodFrequentlyRestarting
#    expr: max(increase(kube_pod_container_status_restarts_total[1h])) by (namespace, pod) > 5
#    for: 10m
#    labels:
#      severity_level: 4
#    annotations:
#      description: Pod {{$labels.namespace}}/{{$labels.pod}} was restarted {{$value}}
#        times within the last hour
#      summary: Pod is restarting frequently
