---
### Cluster issuer, which is only suitable for creating CA or non-trusted certificates
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: selfsigned-no-trust
  {{- include "helm_lib_module_labels" (list . (dict "app" "cert-manager")) | nindent 2 }}
spec:
  selfSigned: {}
---
### Cluster issuer that uses the specified CA to issue certificates
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: selfsigned
  {{- include "helm_lib_module_labels" (list . (dict "app" "cert-manager")) | nindent 2 }}
spec:
  ca:
    secretName: selfsigned-ca-key-pair
