---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  {{- include "helm_lib_module_labels" (list . (dict "app" "cert-manager")) | nindent 2 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
  {{- if .Values.certManager.internal.email }}
    email: "{{ .Values.certManager.internal.email }}"
  {{- end }}
    privateKeySecretRef:
      name: cert-manager-letsencrypt-private-key
    http01: {}
