{{- if or (hasKey .Values.certManager "route53AccessKeyID") (hasKey .Values.certManager "route53SecretAccessKey") }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: route53
  namespace: d8-cert-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "cert-manager")) | nindent 2 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
  {{- if .Values.certManager.internal.email }}
    email: "{{ .Values.certManager.internal.email }}"
  {{- end }}
    privateKeySecretRef:
      name: route53-tls-key
    dns01:
      providers:
      - name: route53
        route53:
          region: us-east-1
          accessKeyID: {{ .Values.certManager.route53AccessKeyID }}
          secretAccessKeySecretRef:
            name: route53
            key: secret-access-key
{{- end }}
