{{- if .Values.flantIntegration.metrics }}
{{- if (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pricing
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "prometheus" "main")) | nindent 2 }}
spec:
  jobLabel: app
  podMetricsEndpoints:
  - port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
      cert:
        secret:
          name: prometheus-scraper-tls
          key: tls.crt
      keySecret:
        name: prometheus-scraper-tls
        key: tls.key
    honorLabels: true
    scrapeTimeout: 25s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_ready]
      regex: "true"
      action: keep
    - regex: endpoint|namespace
      action: labeldrop
  selector:
    matchLabels:
      app: pricing
  namespaceSelector:
    matchNames:
    - d8-{{ .Chart.Name }}
{{- end }}
{{- end }}
