- name: kubernetes.certmanager.certificate
  rules:
  - alert: CertmanagerCertificateExpiredSoon
    expr: |
      max by (name, exported_namespace) (certmanager_certificate_expiration_timestamp_seconds{job="cert-manager"} - time() < 1209600)
    for: 1h
    labels:
      severity_level: "4"
    annotations:
      plk_protocol_version: "1"
      plk_incident_initial_status: "todo"
      description: The certificate {{$labels.exported_namespace}}/{{$labels.name}} will expire in less than 2 weeks
      summary: Certificate will expire soon

  - alert: CertmanagerCertificateExpired
    expr: |
      max by (name, exported_namespace) (certmanager_certificate_expiration_timestamp_seconds{job="cert-manager"} - time() < 0)
    for: 1h
    labels:
      severity_level: "4"
    annotations:
      plk_protocol_version: "1"
      plk_incident_initial_status: "todo"
      description: Certificate {{$labels.exported_namespace}}/{{$labels.name}} expired
      summary: Certificate expired

  - alert: CertmanagerCertificateOrderErrors
    expr: |
      sum by (scheme, host, path, status) (
        rate(
          certmanager_http_acme_client_request_count{status!~"2[0-9][0-9]"}[5m]
        )
      ) > 0
    for: 30m
    labels:
      severity_level: "5"
    annotations:
      plk_protocol_version: "1"
      plk_incident_initial_status: "todo"
      plk_grouped_by__main: D8CertmanagerMalfunctioning,tier=cluster,prometheus=deckhouse
      summary: Certmanager cannot order a certificate.
      description: |
        Cermanager receives responses with the code `{{ $labels.status }}` on requesting {{ $labels.scheme }}://{{ $labels.host }}{{ $labels.path }}.

        It can affect certificates ordering and prolongation. Check certmanager logs for more info.
        `kubectl -n d8-cert-manager logs -l app=cert-manager -c cert-manager` or
        `kubectl -n d8-cert-manager logs -l app=legacy-cert-manager -c cert-manager`

- name: kubernetes.certmanager.orphan_certificate
  rules:
    - alert: D8CertmanagerOrphanSecretsWithoutCorrespondingCertificateResources
      expr: max by (namespace, secret_name, annotation) (d8_orphan_secrets_without_corresponding_certificate_resources==1)
      labels:
        severity_level: "8"
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_incident_initial_status: "todo"
        plk_ignore_labels: "annotation"
        plk_create_group_if_not_exists__d8_certmanager_orphan_secrets_checks_failed: D8CertmanagerOrphanSecretsChecksFailed,tier=~tier
        plk_grouped_by__d8_certmanager_orphan_secrets_checks_failed: D8CertmanagerOrphanSecretsChecksFailed,tier=~tier
        description: |
          Secret {{$labels.namespace}}/{{$labels.secret_name}} has link to non-existent Certificate resource. It is probably garbage. Either delete the secret or remove the `{{$labels.annotation}}` label.
        summary: Secret without corresponding Certificate CR
