{{- if eq .Values.monitoringKubernetesControlPlane.internal.kubeApiserver.accessType "DefaultService" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-apiserver
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "prometheus" "main")) | nindent 2 }}
spec:
  selector:
    matchLabels:
      component: apiserver
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - scheme: https
    port: https
    path: {{ .Values.monitoringKubernetesControlPlane.internal.kubeApiserver.metricsPath }}
    tlsConfig:
      insecureSkipVerify: true
      cert:
        secret:
          name: prometheus-scraper-tls
          key: tls.crt
      keySecret:
        name: prometheus-scraper-tls
        key: tls.key
    relabelings:
    - regex: endpoint|namespace|pod|container
      action: labeldrop
    - targetLabel: job
      replacement: kube-apiserver
    - targetLabel: tier
      replacement: cluster
    - sourceLabels: [__meta_kubernetes_endpoint_ready]
      regex: "true"
      action: keep
{{- end }}
