{{- if .Values.userAuthz.enableMultiTenancy }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-authz-webhook
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "user-authz-webhook")) | nindent 2 }}
data:
  ca.crt: {{ .Values.userAuthz.internal.webhookCA | b64enc }}
  webhook-server.crt: {{ .Values.userAuthz.internal.webhookServerCrt | b64enc }}
  webhook-server.key: {{ .Values.userAuthz.internal.webhookServerKey | b64enc }}
{{- end }}
