{{- if or (hasKey .Values.certManager "cloudflareGlobalAPIKey") (hasKey .Values.certManager "cloudflareEmail") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
  namespace: d8-cert-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "cert-manager")) | nindent 2 }}
data:
  {{- if and (hasKey .Values.certManager "cloudflareGlobalAPIKey") (.Values.certManager.cloudflareGlobalAPIKey) }}
  global-api-key: {{ .Values.certManager.cloudflareGlobalAPIKey | b64enc | quote }}
  {{- else }}
    {{ cat "No key cloudflareGlobalAPIKey in deckhouse configmap" .Values.certManager.cloudflareGlobalAPIKey | fail }}
  {{- end }}
{{- end }}
