---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "speaker")) | nindent 2 }}
data:
  config: |
{{ if .Values.metallb.bgpPeers }}
    peers:
    {{- .Values.metallb.bgpPeers | toYaml | nindent 4 }}
{{- end }}
    address-pools:
    {{- .Values.metallb.addressPools | toYaml | nindent 4 }}
