{{- range $instance := .Values.prometheusPushgateway.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $instance }}
  namespace: kube-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list $ (dict "app" $instance "prometheus.deckhouse.io/target" "prometheus-pushgateway")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9091
  selector:
    app: {{ $instance }}
{{- end }}
