{{- if .Values.global.enabledModules | has "prometheus" }}
  {{- include "helm_lib_prometheus_rules" (list . "d8-monitoring") }}
{{- else }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-empty-helm-workaround
  {{- include "helm_lib_module_labels" (list . (dict "app" .Chart.Name)) | nindent 2 }}
{{- end }}
