---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: annotations-converter
  namespace: d8-cert-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "annotations-converter-webhook")) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:cert-manager:annotations-converter
  {{- include "helm_lib_module_labels" (list . (dict "app" "annotations-converter-webhook")) | nindent 2 }}
rules:
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:cert-manager:annotations-converter
  {{- include "helm_lib_module_labels" (list . (dict "app" "annotations-converter-webhook")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:cert-manager:annotations-converter
subjects:
- kind: ServiceAccount
  name: annotations-converter
  namespace: d8-cert-manager
