---
apiVersion: v1
kind: Service
metadata:
  name: annotations-converter-webhook
  namespace: d8-cert-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "annotations-converter-webhook")) | nindent 2 }}
spec:
  selector:
    heritage: deckhouse
    module: {{ .Chart.Name }}
    app: annotations-converter-webhook
  ports:
  - name: https
    port: 443
    targetPort: 8080
