{{- $context := . }}
{{- range $instance := .Values.monitoringKubernetesControlPlane.internal.kubeEtcd }}
  {{- if eq $instance.accessType "Pod" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-etcd-{{ $instance.name | lower }}
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list $context (dict "prometheus" "main")) | nindent 2 }}
spec:
  selector:
    matchLabels:
      d8-monitoring-control-plane-component: kube-etcd-{{ $instance.name | lower }}
  namespaceSelector:
    matchNames:
    - {{ $instance.pod.podNamespace }}
  endpoints:
  - scheme: {{ $instance.pod.scheme }}
    port: metrics
    path: {{ $instance.metricsPath }}
    tlsConfig:
      insecureSkipVerify: true
      cert:
        secret:
          name: monitoring-control-plane-kube-etcd-client-cert-{{ $instance.name | lower }}
          key: client.crt
      keySecret:
        name: monitoring-control-plane-kube-etcd-client-cert-{{ $instance.name | lower }}
        key: client.key
    relabelings:
    - regex: endpoint|namespace|pod|container
      action: labeldrop
    - targetLabel: job
      replacement: kube-etcd-{{ $instance.name | lower }}
    - targetLabel: tier
      replacement: cluster
    - sourceLabels: [__meta_kubernetes_endpoint_ready]
      regex: "true"
      action: keep
  {{- end }}
{{- end }}
