{{- define "vsphere_csi_config" }}
[Global]
user = {{ .Values.cloudProviderVsphere.internal.username | required ".Values.cloudProviderVsphere.internal.username is required" | quote }}
password = {{ .Values.cloudProviderVsphere.internal.password | required ".Values.cloudProviderVsphere.internal.password is required" | quote }}
insecure-flag = {{ if .Values.cloudProviderVsphere.internal.insecure }}1{{ else }}0{{ end }}
cluster-id = {{ .Values.global.discovery.clusterUUID | quote }}

[VirtualCenter {{ .Values.cloudProviderVsphere.internal.server | required ".Values.cloudProviderVsphere.internal.server is required" | quote }}]
datacenters = {{ .Values.cloudProviderVsphere.internal.datacenter | required ".Values.cloudProviderVsphere.internal.datacenter is required" | quote }}
vm-folder-path = {{ .Values.cloudProviderVsphere.internal.vmFolderPath | required ".Values.cloudProviderVsphere.internal.vmFolderPath is required" }}

[Labels]
region = {{ .Values.cloudProviderVsphere.internal.regionTagCategory | required ".Values.cloudProviderVsphere.internal.regionTagCategory is required" | quote }}
zone = {{ .Values.cloudProviderVsphere.internal.zoneTagCategory | required ".Values.cloudProviderVsphere.internal.zoneTagCategory is required" | quote }}

{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: csi-controller
  namespace: d8-cloud-provider-vsphere
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-controller")) | nindent 2 }}
type: Opaque
data:
  cloud-config: {{ include "vsphere_csi_config" . | b64enc | quote }}
