{{- if .Values.kubeDns.clusterDomainAliases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-kube-dns-sts-pods-hosts-appender-webhook
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "sts-pods-hosts-appender-webhook")) | nindent 2 }}
data:
  ca.crt:  {{ .Values.kubeDns.internal.stsPodsHostsAppenderWebhook.ca  | b64enc }}
  tls.crt: {{ .Values.kubeDns.internal.stsPodsHostsAppenderWebhook.crt | b64enc }}
  tls.key: {{ .Values.kubeDns.internal.stsPodsHostsAppenderWebhook.key | b64enc }}
{{- end }}
