---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-scraper-tls
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.prometheus.internal.prometheusScraperTLS.certificate | b64enc }}
  tls.key: {{ .Values.prometheus.internal.prometheusScraperTLS.key | b64enc }}
