---
apiVersion: v1
kind: Service
metadata:
  name: trickster
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "trickster" "prometheus.deckhouse.io/target" "trickster")) | nindent 2 }}
  annotations:
    prometheus.deckhouse.io/port: "8443"
    prometheus.deckhouse.io/tls: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - port: 443
    name: https
    targetPort: 8443
  selector:
    app: trickster
