{{- if semverCompare "< 1.22" .Values.global.discovery.kubernetesVersion }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    helm.sh/hook: post-upgrade, post-install
    helm.sh/hook-delete-policy: before-hook-creation
  name: legacy-webhook
  namespace: d8-cert-manager
{{ include "helm_lib_module_labels" (list . (dict "app" "legacy-webhook")) | indent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app: legacy-webhook
{{- end }}
