{{- if semverCompare "< 1.22" .Values.global.discovery.kubernetesVersion }}
---
apiVersion: v1
kind: Service
metadata:
  name: legacy-cert-manager-webhook
  namespace: d8-cert-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "legacy-webhook")) | nindent 2 }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: legacy-webhook
{{- end }}
