{{- if eq .Values.monitoringKubernetesControlPlane.internal.kubeControllerManager.accessType "Pod" }}
---
apiVersion: v1
kind: Service
metadata:
  name: d8-monitoring-control-plane-kube-controller-manager
  namespace: {{ .Values.monitoringKubernetesControlPlane.internal.kubeControllerManager.pod.podNamespace }}
  {{- include "helm_lib_module_labels" (list . (dict "d8-monitoring-control-plane-component" "kube-controller-manager")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.monitoringKubernetesControlPlane.internal.kubeControllerManager.pod.port }}
  selector:
    {{- .Values.monitoringKubernetesControlPlane.internal.kubeControllerManager.pod.podSelector | toYaml | nindent 4 }}
{{- end }}
