{{- if (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: controller
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "prometheus" "main" "app" "controller")) | nindent 2 }}
spec:
  jobLabel: app
  podMetricsEndpoints:
    - port: https-metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
        cert:
          secret:
            name: prometheus-scraper-tls
            key: tls.crt
        keySecret:
          name: prometheus-scraper-tls
          key: tls.key
      relabelings:
        - regex: endpoint
          action: labeldrop
        - targetLabel: tier
          replacement: cluster
        - sourceLabels: [__meta_kubernetes_pod_ready]
          regex: "true"
          action: keep
  selector:
    matchLabels:
      app: controller
  namespaceSelector:
    matchNames:
      - d8-{{ .Chart.Name }}
{{- end }}
