{{- if and .Values.global.modules.publicDomainTemplate  .Values.global.clusterIsBootstrapped }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deckhouse-web
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse-web")) | nindent 2 }}
data:
  data.json: >
    {"channel":"{{ $.Values.deckhouseWeb.internal.deckhouseReleaseChannel }}", "version":"{{ $.Values.deckhouseWeb.internal.deckhouseVersion }}", "edition":"{{ $.Values.deckhouseWeb.internal.deckhouseEdition }}"}
{{- end }}
