{{- if and .Values.global.modules.publicDomainTemplate  .Values.global.clusterIsBootstrapped }}
---
kind: Service
apiVersion: v1
metadata:
  name: deckhouse-web
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse-web")) | nindent 2 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: deckhouse-web
{{- end }}
