{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: deckhouse-web
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse-web")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: deckhouse-web
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
    - containerName: web
      maxAllowed:
        cpu: 200m
{{- end }}
