{{- $additional_labels := dict }}
{{- if include "is_istio_in_use" . }}
  {{- $additional_labels = (dict "istio-injection" "enabled") }}
{{- end }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: d8-ingress-nginx
  annotations:
    extended-monitoring.flant.com/enabled: ""
  {{- include "helm_lib_module_labels" (list . $additional_labels) | nindent 2 }}
