{{- if .Values.flantIntegration.madisonAuthKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: madison-proxy
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "madison-proxy")) | nindent 2 }}
data:
  auth-key: {{ .Values.flantIntegration.madisonAuthKey | b64enc | quote }}
{{- end }}
