{{- if .Values.flantIntegration.madisonAuthKey }}
---
apiVersion: v1
kind: Service
metadata:
  name: madison-proxy
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "madison-proxy")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: madison-proxy
---
apiVersion: deckhouse.io/v1alpha1
kind: CustomAlertmanager
metadata:
  name: madison-proxy
  {{- include "helm_lib_module_labels" (list . (dict "app" "madison-proxy")) | nindent 2 }}
spec:
  type: External
  external:
    service:
      namespace: d8-monitoring
      name: madison-proxy
{{- end }}
