---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: d8-descheduler
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
{{- if .Values.descheduler.removePodsViolatingNodeAffinity }}
      "RemovePodsViolatingNodeAffinity":
        enabled: true
        params:
          nodeAffinityType:
          - "requiredDuringSchedulingIgnoredDuringExecution"
{{- else }}
      "RemovePodsViolatingNodeAffinity":
        enabled: false
{{- end }}

{{- if .Values.descheduler.removePodsViolatingInterPodAntiAffinity }}
      "RemovePodsViolatingInterPodAntiAffinity":
        enabled: true
{{- else }}
      "RemovePodsViolatingInterPodAntiAffinity":
        enabled: false
{{- end }}

{{- if .Values.descheduler.removeDuplicates }}
      "RemoveDuplicates":
        enabled: true
{{- else }}
      "RemoveDuplicates":
        enabled: false
{{- end }}

{{- if .Values.descheduler.lowNodeUtilization }}
      "LowNodeUtilization":
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            thresholds:
              "cpu" : 40
              "memory": 50
              "pods": 40
            targetThresholds:
              "cpu" : 80
              "memory": 90
              "pods": 80
{{- else }}
      "LowNodeUtilization":
        enabled: false
{{- end }}

{{- if .Values.descheduler.highNodeUtilization }}
      "HighNodeUtilization":
        enabled: true
        params:
          nodeFit: true
          nodeResourceUtilizationThresholds:
            thresholds:
              "cpu" : 50
              "memory": 50
{{- else }}
      "HighNodeUtilization":
        enabled: false
{{- end }}

{{- if .Values.descheduler.removePodsViolatingNodeTaints }}
      "RemovePodsViolatingNodeTaints":
        enabled: true
{{- else }}
      "RemovePodsViolatingNodeTaints":
        enabled: false
{{- end }}

{{- if .Values.descheduler.removePodsViolatingTopologySpreadConstraint }}
      "RemovePodsViolatingTopologySpreadConstraint":
        enabled: true
{{- else }}
      "RemovePodsViolatingTopologySpreadConstraint":
        enabled: false
{{- end }}

{{- if .Values.descheduler.removePodsHavingTooManyRestarts }}
      "RemovePodsHavingTooManyRestarts":
        enabled: true
        params:
          podsHavingTooManyRestarts:
            podRestartThreshold: 100
            includingInitContainers: true
{{- else }}
      "RemovePodsHavingTooManyRestarts":
        enabled: false
{{- end }}

{{- if .Values.descheduler.podLifeTime }}
      "PodLifeTime":
        enabled: true
        params:
          podLifeTime:
            maxPodLifeTimeSeconds: 86400
            podStatusPhases:
            - "Pending"
{{- else }}
      "PodLifeTime":
        enabled: false
{{- end }}
