---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: d8-cloud-provider-gcp
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: Opaque
data:
  credentials.json: |
    {{- .Values.cloudProviderGcp.internal.providerClusterConfiguration.provider.serviceAccountJSON | b64enc | nindent 4 }}
