apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodegroupconfigurations.deckhouse.io
  labels:
    heritage: deckhouse
    module: node-manager
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: nodegroupconfigurations
    singular: nodegroupconfiguration
    kind: NodeGroupConfiguration
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: &schema
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - content
                - nodeGroups
                - bundles
              properties:
                content:
                  type: string
                  description: The content of the step, can be either go template or plain bash.
                weight:
                  type: integer
                  default: 100
                  description: Order of the step execution.
                nodeGroups:
                  type: array
                  minItems: 1
                  description: List of NodeGroups to apply the step for. To select all NodeGroups you can set '*'.
                  x-examples:
                    - ["master", "worker"]
                    - ["worker"]
                    - ["*"]
                  items:
                    type: string
                bundles:
                  type: array
                  minItems: 1
                  x-examples:
                    - ["ubuntu-lts", "centos-7"]
                    - ["ubuntu-lts"]
                    - ["*"]
                  description: Bundles for step execution. Ex. ubuntu-lts / centos-7. You can set '*' for selecting all bundles.
                  items:
                    type: string
      additionalPrinterColumns:
        - name: Weight
          jsonPath: .spec.weight
          type: integer
        - name: NodeGroups
          jsonPath: .spec.nodeGroups
          type: string
        - name: Bundle
          jsonPath: .spec.bundles
          type: string
