---
apiVersion: v1
kind: Secret
metadata:
  name: node-users
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list $) | nindent 2 }}
type: Opaque
data:
  node-users.json: {{ .Values.nodeManager.internal.nodeUsers | toJson | b64enc }}
